"""baseline_initial

Revision ID: 37c410820056
Revises: 
Create Date: 2026-08-01 11:33:04.308160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c410820056'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annees_scolaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('cloturee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_classe', sa.String(), nullable=True),
    sa.Column('niveau', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('frais_inscription', sa.Float(), nullable=False),
    sa.Column('mensualite', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_code_classe'), 'classes', ['code_classe'], unique=True)
    op.create_table('depenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_depense', sa.String(), nullable=True),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depenses_code_depense'), 'depenses', ['code_depense'], unique=True)
    op.create_table('enseignants',
    sa.Column('matricule', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('specialite', sa.String(), nullable=False),
    sa.Column('heures_hebdo_max', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('matricule'),
    sa.UniqueConstraint('email')
    )
    op.create_table('salles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_salle', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('capacite', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_salles_code_salle'), 'salles', ['code_salle'], unique=True)
    op.create_table('tuteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_tuteur', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('profession', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tuteurs_code_tuteur'), 'tuteurs', ['code_tuteur'], unique=True)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mot_de_passe', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DIRECTEUR', 'COMPTABLE', name='roleutilisateur'), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('tentatives_echouees', sa.Integer(), nullable=False),
    sa.Column('verrouille_jusqua', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_cours', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('volume_horaire', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('matricule_enseignant', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['matricule_enseignant'], ['enseignants.matricule'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cours_code_cours'), 'cours', ['code_cours'], unique=True)
    op.create_table('eleves',
    sa.Column('matricule', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('date_de_naissance', sa.String(), nullable=False),
    sa.Column('lieu_de_naissance', sa.String(), nullable=False),
    sa.Column('sexe', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('acte_naissance', sa.Boolean(), nullable=False),
    sa.Column('carnet_sante', sa.Boolean(), nullable=False),
    sa.Column('jugement_tutelle', sa.Boolean(), nullable=False),
    sa.Column('photo_id', sa.Boolean(), nullable=False),
    sa.Column('certificat_radiation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('tuteur_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tuteur_id'], ['tuteurs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('matricule')
    )
    op.create_table('trimestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('verrouille', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('annee_scolaire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annees_scolaires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('absences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricule_eleve', sa.String(), nullable=False),
    sa.Column('id_cours', sa.Integer(), nullable=True),
    sa.Column('date_absence', sa.Date(), nullable=False),
    sa.Column('justifiee', sa.Boolean(), nullable=False),
    sa.Column('motif', sa.String(), nullable=True),
    sa.Column('justifiee_par_id', sa.Integer(), nullable=True),
    sa.Column('date_justification', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_cours'], ['cours.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['justifiee_par_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matricule_eleve'], ['eleves.matricule'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absences_date_absence'), 'absences', ['date_absence'], unique=False)
    op.create_index(op.f('ix_absences_id_cours'), 'absences', ['id_cours'], unique=False)
    op.create_index(op.f('ix_absences_matricule_eleve'), 'absences', ['matricule_eleve'], unique=False)
    op.create_table('bulletins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule_eleve', sa.String(), nullable=False),
    sa.Column('id_trimestre', sa.Integer(), nullable=False),
    sa.Column('id_classe', sa.Integer(), nullable=False),
    sa.Column('moyenne_generale', sa.Float(), nullable=False),
    sa.Column('rang', sa.Integer(), nullable=True),
    sa.Column('appreciation', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_classe'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_trimestre'], ['trimestres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matricule_eleve'], ['eleves.matricule'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule_eleve', 'id_trimestre', name='uq_bulletin_eleve_trimestre')
    )
    op.create_table('classe_cours',
    sa.Column('id_classe', sa.Integer(), nullable=False),
    sa.Column('id_cours', sa.Integer(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_classe'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_cours'], ['cours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_classe', 'id_cours')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricule_eleve', sa.String(), nullable=False),
    sa.Column('type_document', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['matricule_eleve'], ['eleves.matricule'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_matricule_eleve'), 'documents', ['matricule_eleve'], unique=False)
    op.create_table('inscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_inscription', sa.String(), nullable=True),
    sa.Column('matricule_eleve', sa.String(), nullable=False),
    sa.Column('id_classe', sa.Integer(), nullable=True),
    sa.Column('id_annee_scolaire', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('statut_passage', sa.String(), nullable=False),
    sa.Column('diplome', sa.Boolean(), nullable=False),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('credit_disponible', sa.Float(), nullable=False),
    sa.Column('date_inscription', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_annee_scolaire'], ['annees_scolaires.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_classe'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matricule_eleve'], ['eleves.matricule'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule_eleve', 'id_annee_scolaire', name='uq_inscription_eleve_annee')
    )
    op.create_index(op.f('ix_inscriptions_code_inscription'), 'inscriptions', ['code_inscription'], unique=True)
    op.create_index(op.f('ix_inscriptions_id_annee_scolaire'), 'inscriptions', ['id_annee_scolaire'], unique=False)
    op.create_index(op.f('ix_inscriptions_id_classe'), 'inscriptions', ['id_classe'], unique=False)
    op.create_index(op.f('ix_inscriptions_matricule_eleve'), 'inscriptions', ['matricule_eleve'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('note', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('matricule_eleve', sa.String(), nullable=False),
    sa.Column('id_cours', sa.Integer(), nullable=False),
    sa.Column('id_classe', sa.Integer(), nullable=False),
    sa.Column('matricule_enseignant', sa.String(), nullable=False),
    sa.Column('id_trimestre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_classe'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_cours'], ['cours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_trimestre'], ['trimestres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matricule_eleve'], ['eleves.matricule'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matricule_enseignant'], ['enseignants.matricule'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule_eleve', 'id_cours', 'id_trimestre', name='uq_note_eleve_cours_trimestre')
    )
    op.create_index(op.f('ix_notes_id_classe'), 'notes', ['id_classe'], unique=False)
    op.create_index(op.f('ix_notes_matricule_eleve'), 'notes', ['matricule_eleve'], unique=False)
    op.create_table('seances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cours', sa.Integer(), nullable=False),
    sa.Column('id_classe', sa.Integer(), nullable=False),
    sa.Column('id_annee_scolaire', sa.Integer(), nullable=False),
    sa.Column('id_salle', sa.Integer(), nullable=True),
    sa.Column('jour_semaine', sa.String(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_annee_scolaire'], ['annees_scolaires.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_classe'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_cours'], ['cours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_salle'], ['salles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seances_id_annee_scolaire'), 'seances', ['id_annee_scolaire'], unique=False)
    op.create_index(op.f('ix_seances_id_classe'), 'seances', ['id_classe'], unique=False)
    op.create_index(op.f('ix_seances_id_cours'), 'seances', ['id_cours'], unique=False)
    op.create_index(op.f('ix_seances_id_salle'), 'seances', ['id_salle'], unique=False)
    op.create_table('bulletin_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_bulletin', sa.Integer(), nullable=False),
    sa.Column('id_cours', sa.Integer(), nullable=False),
    sa.Column('moyenne', sa.Float(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_bulletin'], ['bulletins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_cours'], ['cours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('echeances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_inscription', sa.Integer(), nullable=False),
    sa.Column('id_classe', sa.Integer(), nullable=True),
    sa.Column('type_echeance', sa.String(), nullable=False),
    sa.Column('mois', sa.String(), nullable=True),
    sa.Column('date_echeance', sa.Date(), nullable=False),
    sa.Column('montant_du', sa.Float(), nullable=False),
    sa.Column('montant_paye', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('id_echeance_origine', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_classe'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_echeance_origine'], ['echeances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_inscription'], ['inscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_inscription', 'type_echeance', 'mois', name='uq_echeance_inscription_type_mois')
    )
    op.create_index(op.f('ix_echeances_id_inscription'), 'echeances', ['id_inscription'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_paiement', sa.String(), nullable=True),
    sa.Column('id_inscription', sa.Integer(), nullable=False),
    sa.Column('id_echeance', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('numero_recu', sa.String(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_echeance'], ['echeances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_inscription'], ['inscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paiements_code_paiement'), 'paiements', ['code_paiement'], unique=True)
    op.create_index(op.f('ix_paiements_id_echeance'), 'paiements', ['id_echeance'], unique=False)
    op.create_index(op.f('ix_paiements_id_inscription'), 'paiements', ['id_inscription'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paiements_id_inscription'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_id_echeance'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_code_paiement'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_echeances_id_inscription'), table_name='echeances')
    op.drop_table('echeances')
    op.drop_table('bulletin_details')
    op.drop_index(op.f('ix_seances_id_salle'), table_name='seances')
    op.drop_index(op.f('ix_seances_id_cours'), table_name='seances')
    op.drop_index(op.f('ix_seances_id_classe'), table_name='seances')
    op.drop_index(op.f('ix_seances_id_annee_scolaire'), table_name='seances')
    op.drop_table('seances')
    op.drop_index(op.f('ix_notes_matricule_eleve'), table_name='notes')
    op.drop_index(op.f('ix_notes_id_classe'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_inscriptions_matricule_eleve'), table_name='inscriptions')
    op.drop_index(op.f('ix_inscriptions_id_classe'), table_name='inscriptions')
    op.drop_index(op.f('ix_inscriptions_id_annee_scolaire'), table_name='inscriptions')
    op.drop_index(op.f('ix_inscriptions_code_inscription'), table_name='inscriptions')
    op.drop_table('inscriptions')
    op.drop_index(op.f('ix_documents_matricule_eleve'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('classe_cours')
    op.drop_table('bulletins')
    op.drop_index(op.f('ix_absences_matricule_eleve'), table_name='absences')
    op.drop_index(op.f('ix_absences_id_cours'), table_name='absences')
    op.drop_index(op.f('ix_absences_date_absence'), table_name='absences')
    op.drop_table('absences')
    op.drop_table('trimestres')
    op.drop_table('eleves')
    op.drop_index(op.f('ix_cours_code_cours'), table_name='cours')
    op.drop_table('cours')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_tuteurs_code_tuteur'), table_name='tuteurs')
    op.drop_table('tuteurs')
    op.drop_index(op.f('ix_salles_code_salle'), table_name='salles')
    op.drop_table('salles')
    op.drop_table('enseignants')
    op.drop_index(op.f('ix_depenses_code_depense'), table_name='depenses')
    op.drop_table('depenses')
    op.drop_index(op.f('ix_classes_code_classe'), table_name='classes')
    op.drop_table('classes')
    op.drop_table('annees_scolaires')
    # ### end Alembic commands ###
