"""drop_numero_recu

Revision ID: f17c959ae532
Revises: c6b49c380676
Create Date: 2026-08-18 22:01:30.891353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17c959ae532'
down_revision: Union[str, Sequence[str], None] = 'c6b49c380676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paiements', 'numero_recu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paiements', sa.Column('numero_recu', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
